apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  # Keep in mind that this name must match the name of the binding in the event listener YAML
  name: java-app
spec:
  params:
    - name: gitrevision
      value: $(body.head_commit.id)
    - name: gitrepositoryurl
      value: $(body.repository.url)
    - name: contenttype
      value: $(header.Content-Type)

---

apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: java-app
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - name: java-app
      template:
        name: java-app

---

apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: java-app
spec:
  params:
    - name: gitrevision
      description: The git revision
      default: master
    - name: gitrepositoryurl
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        generateName: java-webhook-run-
      spec:
        pipelineRef:
          name: java-pipeline
        resources:
          - name: java-git-tekton
            resourceRef:
              name: java-git-tekton
          - name: java-git
            resourceSpec:
              type: git
              params:
                - name: revision
                  value: master
                - name: url
                  value: https://<sourcecode-url> #EDIT AS NEEDED
          - name: java-git
            resourceSpec:
              type: git
              params:
                - name: revision
                  value: $(params.gitrevision)
                - name: url
                  value: $(params.gitrepositoryurl)
        serviceAccountName: pipeline

