apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: batch
  name: alfatsp-batch-api-st
spec:
  port:
    targetPort: https
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
  to:
    kind: Service
    name: batch-service
    weight: 100
