apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-hello-world
spec:
  params:
    - name: hi
      default: world
    - name: MANIFEST_DIR
      description: The directory in the source code that contains yaml manifests
      default: deployment/ocp
  resources:
    inputs:
    - name: contract-git
      type: git
  steps:
    - name: echo
      image: ubuntu
      command:
        - echo
      args:
        - "hello $(params.hi)"