apiVersion: v1
kind: Secret
metadata:
  name: git-infra-secret
  annotations:
    tekton.dev/git-0: https://github.ibm.com
  labels:
    serviceAccount: pipeline
type: kubernetes.io/basic-auth
stringData:
  username: <username>
  password: <git-access-token>