apiVersion: v1
kind: Secret
metadata:
  name: git-infra-secret
  annotations:
    tekton.dev/git-0: https://us-south.git.cloud.ibm.com
  labels:
    serviceAccount: pipeline
type: kubernetes.io/basic-auth
stringData:
  username: Omar-Gaye
  password: aapoWyzmTDr2gcWSPzFc