apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: java-git
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://<sourcecode-url> #EDIT AS NEEDED

---

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: java-git-tekton
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://<pipeline-url> #EDIT AS NEEDED

---

apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: java-image
spec:
  params:
    - name: url
      value: 'image-registry.openshift-image-registry.svc:5000/$NAMESPACE/java:latest'
  type: image