apiVersion: v1
kind: Secret
metadata:
  name: <secret name> #example: git-infra-secret
  annotations:
    tekton.dev/git-0: https://us-south.git.cloud.ibm.com
  labels:
    serviceAccount: pipeline
type: kubernetes.io/basic-auth
stringData:
  username: <IBM username or e-mail> #example: Omar-Gaye
  password: <personal access token>