apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: batch-pipeline
spec:
  resources:
    - name: batch-git
      type: git
    - name: batch-git-tekton
      type: git
  tasks:
    - name: build
      taskRef:
        name: batch-build-image
      resources:
        inputs:
          - name: batch-git
            resource: batch-git
      params:
        - name: APP_NAME
          value: batch
    - name: deploy
      taskRef:
        name: batch-task-deploy
      resources:
        inputs:
          - name: batch-git-tekton
            resource: batch-git-tekton
      runAfter:
        - build