apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: java-pipeline
spec:
  resources:
    - name: java-git
      type: git
    - name: java-git-tekton
      type: git
  tasks:
    - name: build
      taskRef:
        name: java-build-image
      resources:
        inputs:
          - name: java-git
            resource: java-git
      params:
        - name: APP_NAME
          value: java-app
    - name: deploy
      taskRef:
        name: java-task-deploy
      resources:
        inputs:
          - name: java-git-tekton
            resource: java-git-tekton
      runAfter:
        - build